repos:
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.16.0"
    hooks:
      - id: terraform-docs-go
        # Create docs in terraform directory
        files: (.*\.tf)$
        args: ["markdown", "table", "--output-file", "README.md", "./"]
        sections:
          show:
            - header
            - inputs
            - outputs

        content: |-
          {{ .Header }}

          Terraform to create k3s cluster

          {{ .Providers }}

          {{ .Inputs }}

          {{ .Outputs }}

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.74.1"
    hooks:
      - id: terraform_fmt
        # Format all files with .tf or .tfvars extension
        files: (.*\.tf|\.tfvars)$
